# Generated by Django 4.2.3 on 2023-07-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_orders_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
